- name: Build iOS
  run: |
    cd ios
    xcodebuild -list -workspace *.xcworkspace\
      -workspace *.xcworkspace \
      -scheme PortfelikKaucyjny \
      -configuration Release \
      -sdk iphoneos build